alertmanager_version: "0.27.0"
alertmanager_download_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
alertmanager_download_dir: "/var/tmp"
alertmanager_install_dir: "/opt/alertmanager"