plugin: aws_ec2
regions:
  - eu-central-1
hostnames:
  - instance-id
compose:
  ansible_host: instance_id
keyed_groups:
  - prefix: ""
    key: tags.Project
  - prefix: ""
    key: tags.Tier
  - prefix: tag_Project
    key: tags.Project
  - prefix: tag_Tier
    key: tags.Tier
strict: False
